## Deliverable 2. Create a Customer Travel Destinations Map.

In [14]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [15]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database_copy/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Qaanaaq,GL,77.4840,-69.3632,-17.50,93,99,5.97,overcast clouds
1,1,Takoradi,GH,4.8845,-1.7554,83.88,73,43,9.55,scattered clouds
2,2,Kruisfontein,ZA,-34.0033,24.7314,83.73,53,91,12.44,light rain
3,3,Ushuaia,AR,-54.8000,-68.3000,46.02,70,75,23.02,broken clouds
4,4,Yuncheng,CN,35.0231,110.9928,39.45,66,6,6.35,clear sky

In [16]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [17]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Takoradi,GH,4.8845,-1.7554,83.88,73,43,9.55,scattered clouds
2,2,Kruisfontein,ZA,-34.0033,24.7314,83.73,53,91,12.44,light rain
5,5,Rikitea,PF,-23.1203,-134.9692,76.50,69,42,2.10,light rain
7,7,Tiarei,PF,-17.5333,-149.3333,77.02,74,70,12.68,broken clouds
11,11,Vaini,TO,-21.2000,-175.2000,75.36,94,20,4.61,few clouds
16,16,Georgetown,MY,5.4112,100.3354,79.95,96,40,8.05,moderate rain
17,17,Meulaboh,ID,4.1363,96.1285,77.72,86,99,6.06,moderate rain
19,19,Itarema,BR,-2.9248,-39.9167,88.12,53,97,15.08,overcast clouds
20,20,Busselton,AU,-33.6500,115.3333,79.09,68,0,14.94,clear sky
24,24,Souillac,MU,-20.5167,57.5167,82.78,83,75,6.91,light rain

In [18]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                211
City                   211
Country                208
Lat                    211
Lng                    211
Max Temp               211
Humidity               211
Cloudiness             211
Wind Speed             211
Current Description    211
dtype: int64

In [19]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = city_data_df.dropna().loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
clean_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Takoradi,GH,4.8845,-1.7554,83.88,73,43,9.55,scattered clouds
2,2,Kruisfontein,ZA,-34.0033,24.7314,83.73,53,91,12.44,light rain
5,5,Rikitea,PF,-23.1203,-134.9692,76.50,69,42,2.10,light rain
7,7,Tiarei,PF,-17.5333,-149.3333,77.02,74,70,12.68,broken clouds
11,11,Vaini,TO,-21.2000,-175.2000,75.36,94,20,4.61,few clouds
16,16,Georgetown,MY,5.4112,100.3354,79.95,96,40,8.05,moderate rain
17,17,Meulaboh,ID,4.1363,96.1285,77.72,86,99,6.06,moderate rain
19,19,Itarema,BR,-2.9248,-39.9167,88.12,53,97,15.08,overcast clouds
20,20,Busselton,AU,-33.6500,115.3333,79.09,68,0,14.94,clear sky
24,24,Souillac,MU,-20.5167,57.5167,82.78,83,75,6.91,light rain

In [20]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
clean_hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
clean_hotel_df["Hotel Name"] = ""
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Takoradi,GH,83.88,scattered clouds,4.8845,-1.7554,
2,Kruisfontein,ZA,83.73,light rain,-34.0033,24.7314,
5,Rikitea,PF,76.50,light rain,-23.1203,-134.9692,
7,Tiarei,PF,77.02,broken clouds,-17.5333,-149.3333,
11,Vaini,TO,75.36,few clouds,-21.2000,-175.2000,
16,Georgetown,MY,79.95,moderate rain,5.4112,100.3354,
17,Meulaboh,ID,77.72,moderate rain,4.1363,96.1285,
19,Itarema,BR,88.12,overcast clouds,-2.9248,-39.9167,
20,Busselton,AU,79.09,clear sky,-33.6500,115.3333,
24,Souillac,MU,82.78,light rain,-20.5167,57.5167,

In [22]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in clean_hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
try:
    clean_hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except (IndexErrors):
        print("Hotel not found... skipping " + hotels)

In [23]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df.notnull().sum()

City                   208
Country                208
Max Temp               208
Current Description    208
Lat                    208
Lng                    208
Hotel Name             208
dtype: int64

In [24]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [25]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [27]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))